kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-ssd
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
allowVolumeExpansion: true
---
apiVersion: v1
kind: Service
metadata:
  name: polkadot-node-rpc
spec:
  ports:
  - port: 9933
  selector:
    app: polkadot-node
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: polkadot-node
spec:
  ports:
  - port: 30333
  selector:
    app: polkadot-node
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: polkadot-node
spec:
  selector:
    matchLabels:
      app: polkadot-node
  serviceName: polkadot-node
  replicas: 1
  template:
    metadata:
      labels:
        app: polkadot-node
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: polkadot-node
        image: polkadot-node
        ports:
        - containerPort: 9933
          name: dot-rpc-port
        - containerPort: 30333
          name: dot-p2p-port
        volumeMounts:
        - name: polkadot-node-pv-claim
          mountPath: /polkadot
        envFrom:
        - configMapRef:
            name: polkadot-configmap
        resources:
          limits:
            cpu: 0
        imagePullPolicy: Always
      initContainers:
      - name: polkadot-archive-downloader
        image: polkadot-archive-downloader
        volumeMounts:
        - name: polkadot-node-pv-claim
          mountPath: /polkadot
        env:
        - name: CHAIN
          valueFrom:
            configMapKeyRef:
              name: polkadot-configmap
              key: CHAIN
        - name: ARCHIVE_URL
          valueFrom:
            configMapKeyRef:
              name: polkadot-configmap
              key: ARCHIVE_URL
        imagePullPolicy: Always
  volumeClaimTemplates:
  - metadata:
      name: polkadot-node-pv-claim
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-ssd
