apiVersion: apps/v1
kind: Deployment
metadata:
  name: polkadot-validator-monitor
  labels:
    app: validator-monitor
spec:
  selector:
    matchLabels:
      app: validator-monitor
  template:
    metadata:
      labels:
        app: validator-monitor
    spec:
      containers:
      - name: validator-monitor
        image: validator-monitor
        envFrom:
        - configMapRef:
            name: validator-monitor-configmap
        env:
        - name: NODE_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: polkadot-configmap
              key: NODE_ENDPOINT
        resources:
          limits:
            cpu: 0
        imagePullPolicy: Always
      restartPolicy: Always
