apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: polkadot-payout-cron
spec:
  # every 3 hours
  schedule: "12 */3 * * *"
  concurrencyPolicy:  Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: polkadot-payout-cron
        spec:
          containers:
          - name: payout-cron
            image: payout-cron
            env:
            - name: PAYOUT_ACCOUNT_MNEMONIC
              valueFrom:
                secretKeyRef:
                  name: polkadot-payout-account-mnemonic
                  key: payout-account-mnemonic
            - name: PAYOUT_ACCOUNT_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: polkadot-payout-cron
                  key: PAYOUT_ACCOUNT_ADDRESS
            - name: STASH_ACCOUNT_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: polkadot-payout-cron
                  key: STASH_ACCOUNT_ADDRESS
            resources:
              limits:
                cpu: 0
          restartPolicy: OnFailure
