apiVersion: apps/v1
kind: Deployment
metadata:
  name: polkadot-panic-alerter
spec:
  selector:
    matchLabels:
      app: polkadot-panic-alerter
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: polkadot-panic-alerter
    spec:
      containers:
      - name: polkadot-api-server
        image: simplyvc/polkadot_api_server:1.18.1
        volumeMounts:
        - name: polkadot-api-server-config-vol
          mountPath: /opt/polkadot_api_server/config
        resources:
          limits:
            cpu: 0
      - name: panic-alerter
        image: simplyvc/panic_polkadot:2.0.1
        resources:
          limits:
            cpu: 0
        volumeMounts:
        - name: polkadot-panic-alerter-config-vol
          mountPath: /opt/panic_polkadot/config
        - name: polkadot-panic-alerter-logs-alerts
          mountPath: /opt/panic_polkadot/logs/alerts
        - name: polkadot-panic-alerter-logs-general
          mountPath: /opt/panic_polkadot/logs/general
      volumes:
        - name: polkadot-api-server-config-vol
          configMap:
            name: polkadot-api-server-config
        - name: polkadot-panic-alerter-config-vol
          secret:
            secretName: polkadot-panic-alerter-config-vol
        - name: polkadot-panic-alerter-logs-alerts
          emptyDir: {}
        - name: polkadot-panic-alerter-logs-general
          emptyDir: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: polkadot-api-server-config
  namespace: default
data:
  user_config_main.ini: |
    [api_server]
    port = 3000
  user_config_nodes.ini: |
    [node_1]
    node_name = polkadot_node
    ws_url = ws://polkadot-node-0.polkadot-node:9944
