apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: polkadot-payout-cron
spec:
  concurrencyPolicy:  Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: polkadot-payout-cron
        spec:
          containers:
          - name: payout-cron
            image: payout-cron
            env:
            - name: PAYOUT_ACCOUNT_MNEMONIC
              valueFrom:
                secretKeyRef:
                  name: polkadot-payout-account-mnemonic
                  key: payout-account-mnemonic
            - name: STASH_ACCOUNT_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: polkadot-payout-cron
                  key: STASH_ACCOUNT_ADDRESS
            - name: NODE_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: polkadot-payout-cron
                  key: NODE_ENDPOINT
            resources:
              limits:
                cpu: 0
            imagePullPolicy: Always
          restartPolicy: OnFailure
